device: cpu
dataset_args:
  d_type: train
  sequence_ratio: 0.05
  dataset_path: /home/tom/Projects/MaastrichtAI/research_project2/MA2---Towards-real-time-support-for-a-suicide-prevention-hotline-operators-/filtered_conv
  negative: True
dataloader_args:
  num_workers: 6
  batch_size: 128
  shuffle: True
train_epochs: 10
evaluation: None 